name: Réalisation des Tests

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
    push:

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    coding-standards:
        name: Vérification de la qualité du code (PHP-CS-Fixer)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Installation de PHP et des extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, pdo, pdo_pgsql, intl, zip
                  coverage: none

            - name: Installer Composer
              run: composer install --prefer-dist --no-progress --no-interaction

            - name: Vérifier la qualité du code
              run: composer test:cs:check:ci

    static-analysis:
        name: Analyse statique (PHPStan)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Installation de PHP et des extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, pdo, pdo_pgsql, intl, zip
                  coverage: none

            - name: Installer Composer
              run: composer install --prefer-dist --no-progress --no-interaction

            - name: Warmup cache Symfony
              run: php bin/console cache:warm --env=dev

            - name: Exécuter PHPStan
              run: composer test:phpstan:ci

    test:
        name: Exécution des tests unitaires et fonctionnels (PHPUnit)
        runs-on: ubuntu-latest
        needs: [coding-standards, static-analysis]

        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_DB: ina_zaoui
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U postgres -d ina_zaoui"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        env:
            APP_ENV: test
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Installation de PHP et des extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, pdo, pdo_pgsql, intl, zip
                  coverage: none

            - name: Installer Composer
              run: composer install --prefer-dist --no-progress --no-interaction

            - name: Préparer la base de données de test et exécuter les tests
              run: composer test:phpunit:ci
