# Simple workflow for deploying static content to GitHub Pages
name: Déploiement de la page "test-coverage"

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["preprod"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        env:
            # Set the environment variable to enable code coverage in tests
            APP_ENV: test
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Start Docker
              run: docker compose up -d --build
            - name: Wait for database
              run: |
                  until docker compose exec -T postgres pg_isready -U postgres; do
                      echo "Postgres n'est pas encore prêt..."
                      sleep 2
                  done
            - name: Install Composer dependencies
              run: docker compose exec -T php composer install --no-progress --prefer-dist --no-interaction
            - name: Preparer la base de donnée de test
              run: docker compose exec -T php composer db:test:reset
            - name: Mise à propre du dossier de test-coverage
              run: |
                  rm -rf public/test-coverage
                  mkdir -p public/test-coverage
            - name: Generer le rapport de couverture de code
              run: docker compose exec -T -e XDEBUG_MODE=coverage php composer test:coverage
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  # Upload entire repository
                  path: "./public/test-coverage"
            - name: Stopper Docker
              if: always()
              run: docker compose down -v

    # Single deploy job since we're just deploying
    deploy:
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
