# Simple workflow for deploying static content to GitHub Pages
name: Déploiement de la page "test-coverage"

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
    # Runs on pushes targeting the default branch
    push:
        branches:
            - preprod

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        name: Construction de l'environnement de test
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_DB: ina_zaoui
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd="pg_isready -U postgres -d ina_zaoui"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        env:
            APP_ENV: test
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Installation de PHP et des extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: mbstring, pdo, pdo_pgsql, xdebug, intl, zip
                  coverage: xdebug

            - name: Installer Composer
              run: composer install --prefer-dist --no-progress --no-interaction

            - name: Préparer la base de données de test
              run: composer db:test:reset

            - name: Mise à propre du dossier de test-coverage
              run: |
                  rm -rf public/test-coverage
                  mkdir -p public/test-coverage

            - name: Generer le rapport de couverture de code
              run: XDEBUG_MODE=coverage composer test:coverage

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: "./public/test-coverage"

    deploy:
        name: Déploiement de la page "test-coverage"
        needs: build
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
